### ISSUE TITLE
complex structures

### ISSUE THREAD

**Issue by schmurfy** [mobiruby/mruby-cfunc#22]
I can't find how to do this and this is driving me crazy as that is the last piece of the puzzle I need, can you map the following structure with cfunc and if yes how ?

``` c
struct buffer_struct {
 uint8_t id; 
 uint8_t name[5];
}; 
```

With the ffi gem this would be mapped with:

``` ruby
class BufferStruct < FFI::Struct 
  layout(
      :id,    :uint8, 
      :name,  [:uint8, 5]
    )
end 
```

but I can't find an equivalent with cfunc.

**Comment by schmurfy** [comment]
:(

**Comment by schmurfy** [comment]
@masuidrive can you confirm it is not supported ?
And this is really is not is it a feature you would merge a pull request for ?

I need this for the ffi compatibility layer and I would prefer having it implemented in cfunc and base my on it instead on writing it entirely in my gem.

**Comment by masuidrive** [comment]
Sorry,
CFunc supported it. I'll sample code 2hrs later.

**Comment by masuidrive** [comment]
Sorry, the below code doesn't work correctly.
I'll fix tomorrow in RubyKaigi. :-)

```
CFunc::Struct.define :STest4,
    CFunc::SInt8[10], :x,
    CFunc::SInt16, :y,
    CFunc::SInt32, :z
```

**Comment by schmurfy** [comment]
great, thanks !:)

**Comment by masuidrive** [comment]
Added to support array in struct.
But multi level array isn't support yet.

I take rest two months. and I reboot for MobiRuby from today.
At first, I start to refactoring mruby-cfunc code.

**Comment by schmurfy** [comment]
ok, I don't think the lack of multi level array support is a big problem.
array support in structure was the last piece I really needed to be able to use my ffi layer.
